export const PAKISTAN_BIKES = [
  "Select bike model",
  "Honda CD 70",
  "Honda CG 125",
  "Honda CB 150F",
  "Honda Pridor",
  "Yamaha YBR 125",
  "Yamaha YBR 125G",
  "Suzuki GS 150",
  "Suzuki GD 110",
  "United US 125",
  "United US 70",
  "Road Prince RPM 150",
  "Road Prince Classic 70",
  "Hi Speed Infinity 150",
  "Super Power SP 70",
  "Kawasaki Ninja 250",
  "Keeway RKV 150",
  "Benelli 150",
  "None",
] as const;

export const PAKISTAN_CARS = [
  "Select car model",
  "Suzuki Alto",
  "Suzuki Mehran",
  "Suzuki Cultus",
  "Suzuki Wagon R",
  "Suzuki Swift",
  "Suzuki Bolan",
  "Suzuki Ravi",
  "Toyota Corolla",
  "Toyota Yaris",
  "Toyota Fortuner",
  "Toyota Hilux",
  "Toyota Vitz",
  "Honda City",
  "Honda Civic",
  "Honda BR-V",
  "Kia Sportage",
  "Kia Picanto",
  "Hyundai Tucson",
  "Hyundai Elantra",
  "Hyundai Sonata",
  "Changan Alsvin",
  "Prince Pearl",
  "Proton Saga",
  "MG HS",
  "DFSK Glory 580",
  "None",
] as const;
